# Test the parser on a graph that contains several nodes
# with two edges each.

Exception while running command: LoadGraph heroes staffSuperheroes.csv
java.lang.IllegalArgumentException: no data or bad edges
	at graph.GraphADT$Node.<init>(GraphADT.java:445)
	at graph.GraphADT$Node.add(GraphADT.java:565)
	at marvel.MarvelPaths.buildGraph(MarvelPaths.java:78)
	at marvel.scriptTestRunner.MarvelTestDriver.loadGraph(MarvelTestDriver.java:248)
	at marvel.scriptTestRunner.MarvelTestDriver.loadGraph(MarvelTestDriver.java:243)
	at marvel.scriptTestRunner.MarvelTestDriver.executeCommand(MarvelTestDriver.java:96)
	at marvel.scriptTestRunner.MarvelTestDriver.runTests(MarvelTestDriver.java:70)
	at marvel.scriptTestRunner.ScriptFileTests.runScriptFile(ScriptFileTests.java:153)
	at marvel.scriptTestRunner.ScriptFileTests.checkOutput(ScriptFileTests.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:832)
Exception while running command: ListChildren heroes Ernst-the-Bicycling-Wizard
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "nodes" is null
	at marvel.scriptTestRunner.MarvelTestDriver.listChildren(MarvelTestDriver.java:219)
	at marvel.scriptTestRunner.MarvelTestDriver.listChildren(MarvelTestDriver.java:214)
	at marvel.scriptTestRunner.MarvelTestDriver.executeCommand(MarvelTestDriver.java:93)
	at marvel.scriptTestRunner.MarvelTestDriver.runTests(MarvelTestDriver.java:70)
	at marvel.scriptTestRunner.ScriptFileTests.runScriptFile(ScriptFileTests.java:153)
	at marvel.scriptTestRunner.ScriptFileTests.checkOutput(ScriptFileTests.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:832)
